modLoader="javafml"
loaderVersion="[44,)"
license="LGPL 2.1"

[[mods]]
    modId="andesitefordays"
    version="${file.jarVersion}"
    displayName="Andesite For Days"
    authors="Lex"
    description="A set of simple andesite generators."